plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = 'com.example.railgun'
base { archivesName = 'railgun' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

jar.finalizedBy('reobfJar')
